// <auto-generated />
using Api_App.Data_Access;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_App.Migrations
{
    [DbContext(typeof(Api_AppContext))]
    partial class Api_AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api_App.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Titles")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/5.png&h=200&w=200",
                            Location = "La Boca",
                            Name = "Boca",
                            Titles = 74
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/16.png&h=200&w=200",
                            Location = "Nuñez",
                            Name = "River",
                            Titles = 70
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/11.png&h=200&w=200",
                            Location = "Avellaneda",
                            Name = "Independiente",
                            Titles = 45
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/15.png&h=200&w=200",
                            Location = "Avellaneda",
                            Name = "Racing Club",
                            Titles = 39
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/18.png&h=200&w=200",
                            Location = "Flores",
                            Name = "San Lorenzo",
                            Titles = 22
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/21.png&h=200&w=200",
                            Location = "Liniers",
                            Name = "Velez",
                            Titles = 16
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/8.png&h=200&w=200",
                            Location = "La Plata",
                            Name = "Estudiantes",
                            Titles = 14
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/10.png&h=200&w=200",
                            Location = "Parque Patricios",
                            Name = "Huracan",
                            Titles = 13
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/17.png&h=200&w=200",
                            Location = "Rosario",
                            Name = "Rosario Central",
                            Titles = 11
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/14.png&h=200&w=200",
                            Location = "Rosario",
                            Name = "Newells",
                            Titles = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
